# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com

project_name: ffcss

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
    # so that github does not create a tag in another place
    - git push
    # push the tag
    - git push origin {{ .Tag }}

builds:
  -
    goos: [windows, linux, darwin]
    goarch: [amd64, 386]
    binary: ffcss

archives:
  -
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip

    name_template: '{{.Os}}-{{.Arch}}'

    replacements:
      darwin: macos
      386: 32bit
      amd64: 64bit

    files:
      - LICENSE
      - README.md
      - CHANGELOG.md
      - themes/**
checksum:
  name_template: 'checksums.txt'

# TODO: Homebrew, NFPM, Scoop, Snapcraft (eww), Signing

release:
  prerelease: auto
  name_template: "{{ .Version }}"

changelog:
  skip: true

milestones:
  -
    name_template: "{{ .Version }}"
    close: true
