on: [push, pull_request]
name: Test

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go: [1.15.x]
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        run: make tests
      - name: Upload coverage
        uses: codecov/codecov-action@v2
        with:
          verbose: yes
